### ISSUE TITLE
just installed, nothing works

### ISSUE THREAD

**Issue by puddingepoch** [clonos/site#1]
just installed this, and to my surprise nothing seems to work

cannot login to ssh as simply does not work as if the server doesnt exist
cannot login to the site at all because it thinks no users exist, including root and the ones i made during install.... 
in short, nothing works

edit: 
okay, i had to run cbsd initenv before any of my logins would work... really wish that was something the post install script took care of but whatever

however, my statement stands, even logged in this nothing seems to work right, this is just broken
- i can't fetch any source or bases as it locks up the entire system and renders the web ui unresponsive
- nothing else in the webui even works
this is just so fucking bad, god

**Comment by puddingepoch** [comment]
obviously the root user exists it was made during the install 
i just tried to make another user and it claims it doesnt exist either.... nice os 
i am going to uninstall this now

**Comment by olevole** [comment]
I did not understand anything. put the problem in the right place, with a detailed description. one problem - one Issue.
